### ISSUE TITLE
Develop automated testing framework for workflow (full audit) tests

### ISSUE THREAD

**Issue by michelleblom** [DemocracyDevelopers/colorado-rla#197]
Develop an automated audit workflow test framework that takes a specification of the workflow in a csv file, and hits the right sequence of endpoints (with appropriate data) to execute the workflow.

**Comment by vteague** [comment]
Completed by https://github.com/DemocracyDevelopers/colorado-rla/pull/199
and
https://github.com/DemocracyDevelopers/colorado-rla/pull/202
