### ISSUE TITLE
Client: UI for IRV audit ballots

### ISSUE THREAD

**Issue by vteague** [DemocracyDevelopers/colorado-rla#92]
Implement the UI that allows the audit board to record IRV audit contest data.
CDOS UI designers are actively working on the design - consult with them to learn what it should be like.

This is somewhat dependent on #62 , in that the data can only be received when that card is complete, but the UI implementation can start earlier. Indeed, it may not require #62 at all, but only #90.

**Comment by vteague** [comment]
This is a good thing to start on first, especially if the UI designs are ready, because it's probably the most complex of the new UI features, and the one that faces the general public (i.e. the audit board).

**Comment by vteague** [comment]
The ballot-entering stage is great but the review step still needs the options to be arranged in a table too.

**Comment by cjcarlton** [comment]
There's a pull request for the IRV display on the review page
