### ISSUE TITLE
Client: UI for generating assertions

### ISSUE THREAD

**Issue by vteague** [DemocracyDevelopers/colorado-rla#93]
The prototype of this feature is a simple button, but CDOS has requested more active feedback showing which assertions have been generated. Suggest this should include
- a statement of whether assertion generation has been successful
- the error, if not successful (raire-service errors are expected to be human-readable)
- the winner, if successful.
The CDOS UI design team are looking in to this, and may have suggestions, but it's not as high a priority as the audit board UI.

**Comment by cjcarlton** [comment]
Added spec from Vanessa's suggestion in e-mail:

I suggest that we still just start with one "go" button, which kicks off all the assertion generation, for all IRV contests, with a default timeout. For feedback, we have (appearing on the same page) a table of IRV contests in which the results of assertion generation gradually appear. I'm thinking at least four columns: 
contest name, assertion generation success (Y/N), winner (if any), error/warning.

In the case of an error or warning, depending on that error or warning, you may get a box allowing you to enter a new (presumably longer) time limit, and a button allowing you to try the assertion generation again, for that contest only.
The system would know what kind of errors this might work for (for example, TIME_OUT_FINDING_ASSERTIONS) and would not give you the option for errors that can't be solved by more running time (for example, TIED_WINNERS).

**Comment by vteague** [comment]
Possibly the best way to do this is by adding a list of GenerateAssertionsResponseWithErrors to the CDOS dashboard, rather than explicitly returning it via the http request. Also possibly we need a bit to say whether the error/warning is the kind worth bothering to re-run generation for.

It does seem a bit duplicative to have both GenerateAssertionsResponseWithErrors and GenerateAssertionsSummary, which contain almost identical data. Suspect we can get rid of at least one of these.

**Comment by vteague** [comment]
Update following discussion:

Notes on Audit UI discussion with Charlie.

If there are IRV contests, disable the next button. Activate after first try. (even if there were some failures.) This can just be on the client side.

(TODO: check that if the person succeeds in progressing without assertion generation having run, the IRVComparisonAudits are simply initialized as non-audiable.)

The ones that failed will just be marked as not auditable.

Idea: for the http response, just put (a list of) contestname and status. Then just put the Summary into the database/dashboard. Update the dosDashboard to retrieve the GenerateAssertionsSummaries from the database.

Table starts out simple: contest names and one of 4 status enums (succeeded-done, failed-done, succeeded-try-redo, failed-try-redo).

We'll also look into retrieving the summaries from the database and showing the info in the table - this is nice because it has useful info such as who the apparent winner is, what the error is, etc. There are some database synch issues here which are possibly a bit tricky - we'll look into whether we can guarantee DB updating. Alternatively, it might be fine to be a little delayed if we get the up-to-date status from the http response.

If some fail, the user can try individual ones again. But there's no reason to have separate timer settings for each failed contest - just have one increase-timer option and one button to redo those that can be redone.

Eddie asked that if there are no IRV contests, the assertion-generation page should just be skipped. Apparently the canonicalization page is just skipped if there's nothing to canonicalize - maybe we could look at how that's done and copy the technique. I assume there's something in the dashboard that the client understands?

**Comment by vteague** [comment]
The endpoint takes either no contest (in which case it does all the IRV contests) or one contest, so if there are, for example, two to redo, the client will need to make two separate single-contest calls to the endpoint.

**Comment by cjcarlton** [comment]
Discussion from today's meeting: we decide it would be easiest to store assertion information in the dosState object generated from the dashboard polling (info pulled from generate_assertions_summary table).  This way the generate assertions page can check for assertion data in this one spot and present the assertions table, regenerate assertions button, etc. as needed.

**Comment by vteague** [comment]
The raire-service is now updated so that from the endpoint, for each contest, it returns an abbreviated GenerateAssertionsResponse with two booleans: 'succeded' and 'retry' - it might still be better to use this information immediately to tell the user whether assertion generation succeeded, and give them an opportunity to retry (for those contests where the 'retry' boolean is true), and then separately (presumably more slowly) include the generate_assertions_summary_table data into the dosState object.

**Comment by cjcarlton** [comment]
for mocking test assertion statuses, toss this code block into root.ts after line 168:

        action.data = [
            {contestName: 'Test 1', succeeded: true, retry: false},
            {contestName: 'Test 2', succeeded: false, retry: true},
            {contestName: 'Test 3', succeeded: false, retry: true},
            {contestName: 'Test 4', succeeded: true, retry: false},
            {contestName: 'Test 5', succeeded: true, retry: false},
        ];

**Comment by vteague** [comment]
Looks great @charliecarlton - I'm attaching the screenshot here so you can check it looks like what you expected on my screen too.



![Image](https://github.com/user-attachments/assets/6491605c-62a4-441b-a135-a9a81c0ed862)

**Comment by vteague** [comment]
I like the way there's just one button for generating the assertions, and the user can just click it again to retry, and that the timeout option appears after the first click.

There will possibly (though rarely) some successes that are worth retrying, and some failures that are not worth retrying, but that will fit easily into what you've got.

**Comment by vteague** [comment]
I tested hitting generate-assertions?timeLimitSeconds=2.5
and it all worked fine, so hopefully that bit is easy (integer and float time limits are fine).

**Comment by vteague** [comment]
One very small point is that "Advise retry" might be better than "can retry" - you always *can* retry, you just won't usually get anything better unless something has not quite worked.

**Comment by cjcarlton** [comment]
thanks for looking at it! I pushed an update so it says "Advise Retry" and now it will show those values for successful assertion generations as well.  I'm still considering the button disabling and how to best display the extended assertion generation info that will be in dosState.
