### ISSUE TITLE
Client: UI for assertion generation (extra features)

### ISSUE THREAD

**Issue by vteague** [DemocracyDevelopers/colorado-rla#94]
There are some circumstances where some more user interaction might be necessary during assertion generation. In particular, when the assertion-generation times out for some reason, and we want to give the user the option to re-run the affected contest (only), with a higher time limit.

This needs a bit more thought and discussion with the end-users.

**Comment by cjcarlton** [comment]
Remaining:
-work on dosState refresh
-fix generate assertions button disable while generating (async issue)
-disable Next button only when needed

**Comment by cjcarlton** [comment]
Fixes/Features include:
-dosState refresh should be working now
-Generate Assertions button should now be disabling during generation
-Next button should be disabled before first attempt, but otherwise enabled
-Generate Assertions Page is skipped if there are no IRV contests
